#SPDX-License-Identifier: BSD-3-Clause
---

- name: Install iptables-persistent package
  ansible.builtin.package:
    name: iptables-persistent
    state: latest

- name: Set iptables policies to ACCEPT
  ansible.builtin.iptables:
    chain: "{{ item }}"
    policy: ACCEPT
    ip_version: ipv4
  loop:
    - "INPUT"
    - "FORWARD"
    - "OUTPUT"

- name: Flush iptables
  ansible.builtin.iptables:
    table: "{{ item }}"
    flush: true
  loop: "{{ iptables_tables }}"

- name: Delete custom chains from iptables
  ansible.builtin.command: iptables -t {{ item }} -X
  loop: "{{ iptables_tables }}"
  changed_when: true

- name: Import template of iptables/rules.v4
  ansible.builtin.template:
    src: iptables/rules.v4.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: 0600
    validate: "iptables-restore --test %s"

- name: Restore iptables rules from imported template
  ansible.builtin.command: iptables-restore /etc/iptables/rules.v4
  changed_when: true

- name: Copy auto-restore for booting
  ansible.builtin.copy:
    src: firewall/iptables
    dest: /etc/network/if-up.d/iptables
    owner: root
    group: root
    mode: 751
