#SPDX-License-Identifier: BSD-3-Clause
---

- hosts: proxmox 
  become: true

  tasks:
    - name: Assert that the connection user is root
      ansible.builtin.assert:
        that: ansible_user == "root"
        fail_msg: "Connection failed: Not connected as root user"
        success_msg: "Successfully connected as root"

    - name: Check if 'pveum' exist
      ansible.builtin.stat:
        path: /usr/sbin/pveum
      register: pveum_check

    - name: Fail if 'pveum' not found
      ansible.builtin.fail:
        msg: "pveum is not installed"
      when: not pveum_check.stat.exists

    - name: Assert 'pveum' is executable
      ansible.builtin.assert:
        that: pveum_check.stat.executable
        fail_msg: "'pveum' is not executable"
        success_msg: "'pveum' is executable"

    - name: Run included roles
      ansible.builtin.include_role:
        name: "{{ roles }}"
      loop:
        - common
        - backup
        - audit
        - firewall
        - fail2ban
        - cis-benchmark
      loop_control:
        loop_var: roles