#SPDX-License-Identifier: BSD-3-Clause
---
# tasks file for phalanx
- name: Assert that the connection user is root
  ansible.builtin.assert:
    that: ansible_user == "root"
    fail_msg: "Connection failed: Not connected as root user"
    success_msg: "Successfully connected as root"

- name: Check if 'pveum' exist
  ansible.builtin.stat:
    path: /usr/sbin/pveum
  register: pveum_check

- name: Fail if 'pveum' not found
  ansible.builtin.fail:
    msg: "pveum is not installed"
  when: not pveum_check.stat.exists

- name: Assert 'pveum' is executable
  ansible.builtin.assert:
    that: pveum_check.stat.executable
    fail_msg: "'pveum' is not executable"
    success_msg: "'pveum' is executable"

- name: Import config backup tasks
  ansible.builtin.import_tasks: config-backup.yml

- name: Attempt install all packages
  ansible.builtin.package:
    name: 
      - sudo
      - apt-listchanges
      - unattended-upgrades
    state: latest

- name: Set up 20auto-upgrades
  ansible.builtin.copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Import audit tasks
  ansible.builtin.import_tasks: audit.yml