#SPDX-License-Identifier: BSD-3-Clause
---
# tasks file for phalanx
- name: Assert that the connection user is root
  ansible.builtin.assert:
    that: ansible_user == "root"
    fail_msg: "Connection failed: Not connected as root user"
    success_msg: "Successfully connected as root"

- name: Check if 'pveum' exist
  ansible.builtin.stat:
    path: /usr/sbin/pveum
  register: pveum_check

- name: Fail if 'pveum' not found
  ansible.builtin.fail:
    msg: "pveum is not installed"
  when: not pveum_check.stat.exists

- name: Assert 'pveum' is executable
  ansible.builtin.assert:
    that: pveum_check.stat.executable
    fail_msg: "'pveum' is not executable"
    success_msg: "'pveum' is executable"

- name: Import config backup tasks
  ansible.builtin.import_tasks: modules/config-backup.yml
  when: disable_backup is defined and not disable_backup | bool

- name: Install minimum packages
  ansible.builtin.package:
    name: 
      - sudo
      - apt-listchanges
      - unattended-upgrades
    state: latest

- name: Set up 20auto-upgrades
  ansible.builtin.copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644

- name: Include audit tasks
  ansible.builtin.include_tasks: modules/audit.yml
  when: module_audit | default(true) | bool

- name: Include firewall tasks
  ansible.builtin.include_tasks: modules/firewall.yml
  when: module_firewall | default(true) | bool

- name: Include fail2ban tasks
  ansible.builtin.include_tasks: modules/fail2ban.yml
  when: module_fail2ban | default(true) | bool

- name: Config harden kernel
  ansible.builtin.copy:
    src: "files/kernel/{{ item }}.conf"
    dest: "/etc/sysctl.d/{{ item }}.conf"
    owner: root
    group: root
    mode: 0600
  loop: 
    - "10-tuning"
    - "90-hardening"
  when: module_harden_kernel | default(true) | bool

- name: Load hardened kernel
  ansible.builtin.command: sysctl -p /etc/sysctl.d/*.conf > /dev/null 2>&1
  when: module_harden_kernel | default(true) | bool
  register: sysctl_result
  failed_when: sysctl_result.rc > 1
  changed_when: false

- name: Config harden sudoer
  ansible.builtin.copy:
    src: "files/sudoer/hardening"
    dest: "/etc/sudoers.d/hardening"
    owner: root
    group: root
    mode: 0440
  when: module_harden_sudoer | default(true) | bool

- name: Include CIS Benchmarks
  ansible.builtin.include_tasks: modules/cis-benchmark.yml
  when: disable_cis_modules is defined and not disable_cis_modules | bool